# Generated by Django 4.1.12 on 2023-10-19 16:02

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='http://127.0.0.1:8000/', collection='Study_Buddy_coll'), upload_to=''),
        ),
    ]
