# Generated by Django 4.2.4 on 2023-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='gilgilon', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
