# Generated by Django 4.2.4 on 2023-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='I love Python', max_length=200),
            preserve_default=False,
        ),
    ]
