# Generated by Django 4.2.4 on 2023-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
