# Generated by Django 4.2.4 on 2023-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(blank=True),
        ),
    ]
