# Generated by Django 4.1.13 on 2024-02-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_created',
            new_name='host',
        ),
    ]
