# Generated by Django 4.1.12 on 2023-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.TextField(blank=True, max_length=10000000),
        ),
    ]
