# Generated by Django 4.1.12 on 2023-11-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
